services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

  wordpress:
    container_name: wordpress
    build: wordpress
    restart: always
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

networks:
  custom_network:

volumes:
  wordpress_data:
