services:
  nginx:
    container_name: nginx
    build: nginx
    ports:
      - 443:443
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

  wordpress:
    container_name: wordpress
    build: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - custom_network

  mariadb:
    container_name: mariadb
    build: mariadb
    restart: always
    networks:
      - custom_network
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
networks:
  custom_network:

volumes:
  wordpress_data:
  mariadb_data:
